version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "${APP_PORT}:80"
    links:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
      - app-data:/var/www/html
    depends_on:
      - php
      - database
      - init_php

  php:
    build:
      context: .
      dockerfile: ./docker/fpm/Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - app-data:/var/www/html
    ports:
      - 8177:9000
    depends_on:
      - database
      - init_php

  init_php:
    build:
      context: .
      dockerfile: ./docker/init/Dockerfile
    container_name: ${APP_NAME}_init
    depends_on: 
      - database
    volumes:
      - app-data:/var/www/html

  database:
    image: mysql:8.0
    container_name: ${APP_NAME}_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql

volumes:
  app-data: