version: '3'

networks:
  webapp:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "${APP_PORT}:80"
    links:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
      - app-data:/var/www/html
    depends_on:
      - php
      - database
    networks:
      - webapp

  php:
    build:
      context: .
      dockerfile: ./docker/fpm/Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
      - app-data:/var/www/html
    depends_on:
      - database
    networks:
      - webapp

  database:
    image: mysql:8.0
    container_name: ${APP_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - webapp

volumes:
  app-data: